services:
  server:
    build:
      context: .
      target: dev
    environment:
      NODE_ENV: production
      DB_CONN: ${DB_CONN}
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules


